name: Node.js Package

on:
  release:
    types: [created]
  push:
    paths:
      - '02project/**'  # Tracks changes in the 02project folder and its subfolders
  pull_request:
    paths:
      - '02project/**'  # Tracks changes in the 02project folder and its subfolders

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
        working-directory: ./02project  # Specify the working directory (02project folder)
      - name: Run tests
        run: npm test
        working-directory: ./02project  # Specify the working directory (02project folder)

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - name: Install dependencies
        run: npm ci
        working-directory: ./02project  # Specify the working directory (02project folder)
      - name: Publish package
        run: npm publish
        working-directory: ./02project  # Specify the working directory (02project folder)
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
