name: Deploy React App

on:
  push:
    branches:
      - main  # Deploy only when pushing to 'main'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: 02project/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: 02project

      - name: Build project
        run: npm run build
        working-directory: 02project

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./02project/dist
          branch: gh-pages  # Deploy to the 'gh-pages' branch
