name: Deploy React App

on:
  push:
    branches:
      - main  # Change if your default branch is different

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'  # Uses npm for caching dependencies

      - name: Install dependencies
        run: npm install --package-lock-only  # Creates a lock file if missing

      - name: Build project
        run: npm run build  # This assumes you have a build script in package.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Adjust this if your build directory is different
